apiVersion: v1
kind: ConfigMap
metadata:
  name: graylog-config
  namespace: testgray1010mn
data:
  graylog.conf: |
    # HTTP bind address
    http_bind_address = 0.0.0.0:9000
    
    # MongoDB URI
    mongodb_uri = mongodb://mongodb-service:27017/graylog
    
    # OpenSearch hosts
    elasticsearch_hosts = http://opensearch-service:9200
    
    # Security
    password_secret = somepasswordpepper
    root_password_sha2 = 8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    
    # Directories
    data_dir = /usr/share/graylog/data
    plugin_dir = /usr/share/graylog/plugin
    message_journal_dir = /usr/share/graylog/data/journal
    
    # Configuration
    root_timezone = UTC
    message_journal_enabled = true
    rotation_strategy = count
    retention_strategy = delete
    elasticsearch_max_number_of_indices = 20
    
    # Node ID file
    node_id_file = /usr/share/graylog/data/node-id
